Buildfile: /home/ec2-user/ASL-MQ/build.xml

compile:

jar:

run:
     [java] Message server running
     [java] ########## Middleware Report ##########
     [java] Req#	 Time	 Resp	 Rate	 Recv#	 Throughput
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Get connection error:0 ms.
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Get connection error:0 ms.
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Retry Count: 0
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Get connection error:0 ms.
     [java] Exception in thread "pool-1-thread-1" java.lang.NullPointerException
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Get connection error:0 ms.
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Retry Count: 0
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Get connection error:0 ms.
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Retry Count: 0
     [java] Exception in thread "pool-1-thread-7" java.lang.NullPointerException
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Get connection error:6 ms.
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Retry Count: 0
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Get connection error:2 ms.
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Get connection error:0 ms.
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Retry Count: 0
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Get connection error:0 ms.
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Retry Count: 0
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Get connection error:0 ms.
     [java] Exception in thread "pool-1-thread-10" java.lang.NullPointerException
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Retry Count: 0
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Retry Count: 0
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Retry Count: 0
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Retry Count: 0
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Get connection error:0 ms.
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Retry Count: 0
     [java] Exception in thread "pool-1-thread-4" java.lang.NullPointerException
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Exception in thread "pool-1-thread-12" java.lang.NullPointerException
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Get connection error:0 ms.
     [java] Exception in thread "pool-1-thread-9" java.lang.NullPointerException
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Exception in thread "pool-1-thread-2" java.lang.NullPointerException
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Exception in thread "pool-1-thread-11" java.lang.NullPointerException
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Retry Count: 0
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Get connection error:0 ms.
     [java] Nov 08, 2014 11:57:59 AM main.java.ch.ethz.systems.asl.service.db.DBService getConnection
     [java] INFO: Retry Count: 0
     [java] Exception in thread "pool-1-thread-5" java.lang.NullPointerException
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Exception in thread "pool-1-thread-8" java.lang.NullPointerException
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Exception in thread "pool-1-thread-6" Exception in thread "pool-1-thread-13" java.lang.NullPointerException
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Exception in thread "pool-1-thread-18" java.lang.NullPointerException
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] java.lang.NullPointerException
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.getConnection(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] java.sql.SQLException: sql:SELECT func_insert_queue('queue11')
     [java] ERROR: duplicate key value violates unique constraint "queue_qname_key"
     [java]   Detail: Key (qname)=(queue11) already exists.
     [java]   Where: SQL function "func_insert_queue" statement 1
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.select(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.sqlSelect(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.processSend(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] java.sql.SQLException: sql:SELECT func_insert_queue('queue11')
     [java] ERROR: duplicate key value violates unique constraint "queue_qname_key"
     [java]   Detail: Key (qname)=(queue11) already exists.
     [java]   Where: SQL function "func_insert_queue" statement 1
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.select(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.sqlSelect(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.processSend(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] java.sql.SQLException: sql:SELECT func_insert_queue('queue11')
     [java] ERROR: duplicate key value violates unique constraint "queue_qname_key"
     [java]   Detail: Key (qname)=(queue11) already exists.
     [java]   Where: SQL function "func_insert_queue" statement 1
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.select(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.sqlSelect(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.processSend(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] java.sql.SQLException: sql:SELECT func_insert_queue('queue11')
     [java] ERROR: duplicate key value violates unique constraint "queue_qname_key"
     [java]   Detail: Key (qname)=(queue11) already exists.
     [java]   Where: SQL function "func_insert_queue" statement 1
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.select(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.sqlSelect(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.processSend(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] java.sql.SQLException: sql:SELECT func_insert_queue('queue11')
     [java] ERROR: duplicate key value violates unique constraint "queue_qname_key"
     [java]   Detail: Key (qname)=(queue11) already exists.
     [java]   Where: SQL function "func_insert_queue" statement 1
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.select(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.sqlSelect(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.processSend(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] java.sql.SQLException: sql:SELECT func_insert_queue('queue17')
     [java] ERROR: duplicate key value violates unique constraint "queue_qname_key"
     [java]   Detail: Key (qname)=(queue17) already exists.
     [java]   Where: SQL function "func_insert_queue" statement 1
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.select(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.sqlSelect(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.processSend(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] java.sql.SQLException: sql:SELECT func_insert_queue('queue18')
     [java] ERROR: duplicate key value violates unique constraint "queue_qname_key"
     [java]   Detail: Key (qname)=(queue18) already exists.
     [java]   Where: SQL function "func_insert_queue" statement 1
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.select(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.sqlSelect(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.processSend(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] java.sql.SQLException: sql:SELECT func_insert_queue('queue18')
     [java] ERROR: duplicate key value violates unique constraint "queue_qname_key"
     [java]   Detail: Key (qname)=(queue18) already exists.
     [java]   Where: SQL function "func_insert_queue" statement 1
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.select(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.sqlSelect(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.processSend(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] java.sql.SQLException: sql:SELECT func_insert_queue('queue18')
     [java] ERROR: duplicate key value violates unique constraint "queue_qname_key"
     [java]   Detail: Key (qname)=(queue18) already exists.
     [java]   Where: SQL function "func_insert_queue" statement 1
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.select(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.sqlSelect(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.processSend(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] java.sql.SQLException: sql:SELECT func_insert_queue('queue19')
     [java] ERROR: duplicate key value violates unique constraint "queue_qname_key"
     [java]   Detail: Key (qname)=(queue19) already exists.
     [java]   Where: SQL function "func_insert_queue" statement 1
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.select(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.sqlSelect(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.processSend(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] java.sql.SQLException: sql:SELECT func_insert_queue('queue19')
     [java] ERROR: duplicate key value violates unique constraint "queue_qname_key"
     [java]   Detail: Key (qname)=(queue19) already exists.
     [java]   Where: SQL function "func_insert_queue" statement 1
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.select(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.sqlSelect(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.processSend(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] java.sql.SQLException: sql:SELECT func_insert_queue('queue19')
     [java] ERROR: duplicate key value violates unique constraint "queue_qname_key"
     [java]   Detail: Key (qname)=(queue19) already exists.
     [java]   Where: SQL function "func_insert_queue" statement 1
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.select(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.sqlSelect(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.processSend(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] java.sql.SQLException: sql:SELECT func_insert_queue('queue19')
     [java] ERROR: duplicate key value violates unique constraint "queue_qname_key"
     [java]   Detail: Key (qname)=(queue19) already exists.
     [java]   Where: SQL function "func_insert_queue" statement 1
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.select(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.sqlSelect(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.processSend(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] java.sql.SQLException: sql:SELECT func_insert_queue('queue19')
     [java] ERROR: duplicate key value violates unique constraint "queue_qname_key"
     [java]   Detail: Key (qname)=(queue19) already exists.
     [java]   Where: SQL function "func_insert_queue" statement 1
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.select(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.sqlSelect(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.processSend(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] java.sql.SQLException: sql:SELECT func_insert_queue('queue20')
     [java] ERROR: duplicate key value violates unique constraint "queue_qname_key"
     [java]   Detail: Key (qname)=(queue20) already exists.
     [java]   Where: SQL function "func_insert_queue" statement 1
     [java] 	at main.java.ch.ethz.systems.asl.service.db.DBService.select(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.util.DbUtil.sqlSelect(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.processSend(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.msgExecution(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.runMsgManagement(Unknown Source)
     [java] 	at main.java.ch.ethz.systems.asl.service.middleware.MessageService.run(Unknown Source)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] 1000	 54899	 54	 18	 969	 83
     [java] 2000	 104856	 52	 19	 1969	 133
     [java] 3000	 156844	 52	 19	 2970	 176
     [java] 4000	 206031	 51	 19	 3970	 200
     [java] 5000	 257198	 51	 19	 4974	 217
     [java] 6000	 309227	 51	 19	 5969	 230
     [java] 7000	 362422	 51	 19	 6971	 250
     [java] 8000	 423056	 52	 18	 7968	 250
     [java] 9000	 482072	 53	 18	 8969	 257
     [java] 10000	 542155	 54	 18	 9969	 263
     [java] 11000	 603329	 54	 18	 10969	 268
     [java] 12000	 667512	 55	 17	 11969	 266
     [java] 13000	 733116	 56	 17	 12973	 270
     [java] 14000	 801065	 57	 17	 13969	 269
     [java] 15000	 872273	 58	 17	 14968	 272
     [java] 16000	 946374	 59	 16	 15969	 271
     [java] 17000	 1026932	 60	 16	 16968	 269
     [java] 18000	 1102413	 61	 16	 17970	 268
     [java] 19000	 1177255	 61	 16	 18969	 267
     [java] 20000	 1251811	 62	 15	 19968	 266
     [java] 21000	 1326696	 63	 15	 20969	 265
     [java] 22000	 1409102	 64	 15	 21969	 265
     [java] 23000	 1492757	 64	 15	 22968	 261
     [java] 24000	 1577930	 65	 15	 23972	 260
     [java] 25000	 1672058	 66	 14	 24969	 257
     [java] 26000	 1758137	 67	 14	 25968	 257
     [java] 27000	 1846400	 68	 14	 26968	 254
     [java] 28000	 1941256	 69	 14	 27968	 252
     [java] 29000	 2039475	 70	 14	 28970	 250
     [java] 30000	 2142978	 71	 14	 29968	 247
     [java] 31000	 2254848	 72	 13	 30968	 244
     [java] 32000	 2372470	 74	 13	 31968	 240
     [java] 33000	 2491082	 75	 13	 32968	 237
     [java] 34000	 2604134	 76	 13	 33969	 234
     [java] 35000	 2718172	 77	 12	 34968	 231
     [java] 36000	 2839362	 78	 12	 35970	 229
     [java] 37000	 2967352	 80	 12	 36969	 225
     [java] 38000	 3196453	 84	 11	 37968	 217
     [java] 39000	 3407282	 87	 11	 38968	 209
     [java] 40000	 3595093	 89	 11	 39968	 205
     [java] 41000	 3780665	 92	 10	 40968	 200
     [java] 42000	 4036806	 96	 10	 41968	 192
     [java] 43000	 4267570	 99	 10	 42968	 186
     [java] 44000	 4483587	 101	 9	 43969	 182
     [java] 45000	 4714737	 104	 9	 44968	 178
     [java] 46000	 4967897	 107	 9	 45969	 173
     [java] 47000	 5193062	 110	 9	 46968	 170
     [java] 48000	 5436223	 113	 8	 47968	 166
     [java] 49000	 5723919	 116	 8	 48969	 161
     [java] 50000	 5947408	 118	 8	 49969	 158
     [java] 51000	 6190946	 121	 8	 50968	 155
     [java] 52000	 6526934	 125	 7	 51968	 151
     [java] 53000	 6776634	 127	 7	 52968	 148
     [java] 54000	 7019116	 129	 7	 53969	 146
     [java] 55000	 7361083	 133	 7	 54968	 142
     [java] 56000	 7652967	 136	 7	 55969	 139
     [java] 57000	 7904640	 138	 7	 56968	 137
     [java] 58000	 8222670	 141	 7	 57968	 134
     [java] 59000	 8544159	 144	 6	 58968	 132
     [java] 60000	 8815060	 146	 6	 59968	 130
     [java] 61000	 9169946	 150	 6	 60968	 127
     [java] 62000	 9480457	 152	 6	 61970	 125
     [java] 63000	 9778358	 155	 6	 62968	 123
     [java] 64000	 10142554	 158	 6	 63968	 121
     [java] 65000	 10466319	 161	 6	 64969	 119
     [java] 66000	 10781492	 163	 6	 65969	 118
     [java] 67000	 11154148	 166	 6	 66968	 115
     [java] 68000	 11488698	 168	 5	 67969	 114
     [java] 69000	 11815768	 171	 5	 68968	 112
     [java] 70000	 12205278	 174	 5	 69968	 110
     [java] 71000	 12557770	 176	 5	 70968	 109
     [java] 72000	 12911876	 179	 5	 71968	 107
     [java] 73000	 13319037	 182	 5	 72968	 106
     [java] 74000	 13648352	 184	 5	 73968	 105
     [java] 75000	 14058608	 187	 5	 74968	 103
     [java] 76000	 14395114	 189	 5	 75968	 102
     [java] 77000	 14770121	 191	 5	 76968	 101
     [java] 78000	 15153691	 194	 5	 77968	 100
     [java] 79000	 15493071	 196	 5	 78968	 98
     [java] 80000	 15936336	 199	 5	 79968	 97
     [java] 81000	 16279505	 200	 4	 80968	 96
     [java] 82000	 16728098	 204	 4	 81968	 95
     [java] 83000	 17135121	 206	 4	 82968	 94
     [java] 84000	 17474679	 208	 4	 83969	 93
     [java] 85000	 17980298	 211	 4	 84968	 92
     [java] 86000	 18361488	 213	 4	 85968	 91
     [java] 87000	 18813162	 216	 4	 86968	 90
     [java] 88000	 19248355	 218	 4	 87968	 89
     [java] 89000	 19643643	 220	 4	 88968	 88
     [java] 90000	 20159304	 223	 4	 89968	 87
     [java] 91000	 20572082	 226	 4	 90968	 86
     [java] 92000	 21008728	 228	 4	 91968	 85
     [java] 93000	 21528996	 231	 4	 92969	 84
     [java] 94000	 21943724	 233	 4	 93968	 83
     [java] 95000	 22454384	 236	 4	 94968	 82
     [java] 96000	 22945544	 239	 4	 95968	 81
     [java] 97000	 23375695	 240	 4	 96968	 81
     [java] 98000	 23938109	 244	 4	 97968	 80
     [java] 99000	 24424669	 246	 4	 98968	 79
     [java] 100000	 24822643	 248	 4	 99968	 78
     [java] 101000	 25462492	 252	 3	 100968	 77
     [java] 102000	 25923625	 254	 3	 101968	 77
     [java] 103000	 26358114	 255	 3	 102968	 76
     [java] 104000	 26968821	 259	 3	 103968	 75
     [java] 105000	 27498567	 261	 3	 104968	 74
     [java] 106000	 27920063	 263	 3	 105969	 74
     [java] 107000	 28570871	 267	 3	 106968	 73
     [java] 108000	 29075402	 269	 3	 107968	 72
     [java] 109000	 29526492	 270	 3	 108968	 72
     [java] 110000	 30186482	 274	 3	 109968	 71
     [java] 111000	 30706664	 276	 3	 110969	 71
     [java] 112000	 31282027	 279	 3	 111968	 70
     [java] 113000	 31863086	 281	 3	 112968	 69
     [java] 114000	 32357221	 283	 3	 113968	 69
     [java] 115000	 33038242	 287	 3	 114968	 68
     [java] 116000	 33560725	 289	 3	 115968	 67
     [java] 117000	 34103876	 291	 3	 116968	 67
     [java] 118000	 34762182	 294	 3	 117968	 66
     [java] 119000	 35306120	 296	 3	 118968	 66
     [java] 119146	 35391979	 297	 3	 119114	 66
     [java] Message server shutdown

BUILD SUCCESSFUL
Total time: 30 minutes 5 seconds
